export interface LabItem {
  slug: string;
  title: string;
  category: "CyArt Tech" | "Edunet Foundation";
  objective: string;
  architecture: {
    description: string;
    steps: string[];
  };
  stack: string[];
  engineeringWork: string[];
  results: string[];
  lessons: string[];
}

export const labItems: LabItem[] = [
  {
    slug: "news-sentiment-pipeline",
    title: "News Sentiment Pipeline",
    category: "CyArt Tech",
    objective: "Engineered an automated crawler and ingestion pipeline that parses RSS feeds in real time to assess financial and technical market sentiment.",
    architecture: {
      description: "Distributed async workers processing live XML streams into an NLP pipeline.",
      steps: [
        "Cron tasks scan 20 RSS news endpoints every 60 seconds.",
        "Payload filter parses XML articles and handles duplicate stories using hashes.",
        "Text chunks are analyzed by three sentiment models (VADER, FinBERT, and a custom classifier).",
        "Results are indexed in a time-series cache."
      ]
    },
    stack: ["Python", "FastAPI", "FinBERT", "Redis", "Celery"],
    engineeringWork: [
      "Wrote non-blocking parsing adapters that process 494 headlines across 20 RSS feeds concurrently.",
      "Optimized model inference queue, reaching average processing speed of 19 headlines/second.",
      "Set up a deduplication index storing story hashes in Redis to skip repetitive content."
    ],
    results: [
      "Processed 494 headlines concurrently.",
      "Tracked across 20 global tech RSS sources.",
      "Reached an ingestion rate of 19 headlines/sec.",
      "Integrated 3 parallel NLP engines for cross-validation.",
      "Generated 1,877+ sentiment classifications.",
      "20% ingestion performance improvement."
    ],
    lessons: [
      "XML formatting rules are highly inconsistent; built-in regex sanitizers are crucial to normalize titles.",
      "GPU memory leaks in Celery workers require auto-restarting processes after every 1000 inferences."
    ]
  },
  {
    slug: "surveillance-engineering",
    title: "Surveillance Engineering",
    category: "CyArt Tech",
    objective: "Built a high-integrity multi-stream RTSP feed monitoring pipeline to detect network video drops, tamper signs, and frame-rate discrepancies.",
    architecture: {
      description: "Asynchronous OpenCV capture loops feeding frame integrity assessors.",
      steps: [
        "OpenCV hooks onto 4 distinct camera network simulation links.",
        "Buffer threads grab frame matrices independently from processing cycles.",
        "An integrity assessor calculates frame differences and monitors for signal loss.",
        "Trigger reports alert monitoring consoles if frame rate drops below thresholds."
      ]
    },
    stack: ["Python", "OpenCV", "FFmpeg", "GStreamer"],
    engineeringWork: [
      "Developed a custom video stream capture thread to bypass standard OpenCV buffer lag.",
      "Configured 2 motion-estimation algorithms executing in parallel (MOG2 background subtraction and optical flow).",
      "Wrote 4 structural frame integrity tests verifying black screen, color bars, frozen streams, and high noise."
    ],
    results: [
      "Orchestrates 4 concurrent live camera simulation streams.",
      "Operates at an average of 7.4 frames per second per stream.",
      "Utilizes 2 specialized motion detection algorithms.",
      "Maintains 4 real-time stream integrity safety checks."
    ],
    lessons: [
      "Network packets fluctuate; socket timeouts must be dynamic to prevent locks on lost connections.",
      "RTSP stream buffer overflow is mitigated by dropping older frames from queue blocks."
    ]
  },
  {
    slug: "voice-cloning-benchmarks",
    title: "Voice Cloning Benchmarks",
    category: "CyArt Tech",
    objective: "Created a rigorous comparative testing framework evaluating neural text-to-speech voice cloning systems.",
    architecture: {
      description: "Audio benchmarking harness comparing synthetic speech outputs against target reference waveforms.",
      steps: [
        "Target reference audio is normalized for sample rate and decibel range.",
        "Audio is run through XTTS-v2 and VALL-E-X generation scripts.",
        "Cosine similarity measures distance between speaker embedding vectors.",
        "Wav2Vec evaluates output semantic clarity."
      ]
    },
    stack: ["Python", "XTTS-v2", "VALL-E-X", "PyTorch", "Librosa"],
    engineeringWork: [
      "Developed an automated evaluation harness running 15 distinct text-to-speech speaker cloning test variations.",
      "Compared cosine distances between audio embeddings generated by different models.",
      "Evaluated performance across noise profiles, accents, and phrase complexities."
    ],
    results: [
      "Compared performance metrics of XTTS-v2 vs VALL-E-X architectures.",
      "Executed 15 speaker configuration test cycles.",
      "Averaged a Speaker Embedding Cosine Similarity score of 0.965.",
      "Achieved sub-2.1s generation times on consumer GPUs."
    ],
    lessons: [
      "Reference audio under 3 seconds produces high speaker distortion; 5-10s clips are ideal for stability.",
      "Model outputs suffer from high-frequency artifacts if sample rate conversions are not strictly matching."
    ]
  },
  {
    slug: "cinescope-build-journey",
    title: "CineScope Build Journey",
    category: "Edunet Foundation",
    objective: "Engineered and shipped a clean, single-page search web application using React client architectures and validation filters.",
    architecture: {
      description: "Client search app connected to verified Node proxies to bypass rate limit blocks.",
      steps: [
        "React search input fields capture user typing strings.",
        "Client validator evaluates length and characters prior to network requests.",
        "Node proxy forwards verified queries to OMDb API services.",
        "React elements animate layout changes dynamically."
      ]
    },
    stack: ["React", "Express.js", "Node.js", "OMDb API"],
    engineeringWork: [
      "Configured client-side debouncing limits (300ms delay) to prevent typing queries from draining API quotas.",
      "Built 6 custom state validator tests checking empty inputs, character limits, specials, and numerical filters.",
      "Integrated Express route middlewares resolving cross-origin resource sharing errors in local testing environments."
    ],
    results: [
      "Implemented 8 core client features including favorites list and search histories.",
      "Set up 6 strict query parameter validation checks.",
      "Resolved 5 critical CORS and API key exposure bugs.",
      "Fully documented and released under the open-source MIT license."
    ],
    lessons: [
      "Exposing API tokens in client scripts is dangerous; a simple server proxy prevents security vulnerabilities.",
      "Network failures should not block client interaction; setup fallback mock databases."
    ]
  }
];
